name=tinyolfarve
version=1.0.1
author=Thomas Ascher <thomas.ascher@gmx.at>
maintainer=Thomas Ascher <thomas.ascher@gmx.at>
sentence=sRGB rendering of SRM/EBC beer color values.
paragraph=A lightweight port of cppolfarve.
category=Other
url=https://github.com/aschet/tinyolfarve
architectures=*
includes=tinyolfarve.hpp
